import os
from datetime import datetime

class ReportGenerator:
    def __init__(self, output_dir):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def save_report(self, alerts, rca_texts=None):
        """Saves a markdown report of the findings."""
        timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"incident_report_{timestamp_str}.md"
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w') as f:
            f.write(f"# VSMK-AI-SOC Incident Report\n")
            f.write(f"**Generated:** {datetime.now()}\n\n")
            
            f.write("## Executive Summary\n")
            f.write(f"Total Alerts Detected: {len(alerts)}\n")
            critical_count = sum(1 for a in alerts if a.get('severity') == 'CRITICAL')
            f.write(f"Critical Incidents: {critical_count}\n\n")
            
            f.write("## Alert Details\n")
            if not alerts:
                f.write("No alerts detected.\n")
            else:
                for alert in alerts:
                    f.write(f"### [{alert.get('severity', 'UNKNOWN')}] {alert['rule']}\n")
                    f.write(f"- **ID:** {alert['id']}\n")
                    f.write(f"- **Time:** {alert['timestamp']}\n")
                    f.write(f"- **Source:** {alert['source_ip']}\n")
                    f.write(f"- **Details:** {alert['details']}\n")
                    if 'ai_analysis' in alert:
                        f.write(f"- **AI Analysis:** {alert['ai_analysis']}\n")
                    f.write("\n")
            
            if rca_texts:
                f.write("## Root Cause Analysis (RCA) Deep Dives\n")
                for rca in rca_texts:
                    f.write("```text\n")
                    f.write(rca)
                    f.write("\n```\n\n")
            
            f.write("---\n")
            f.write("Generated by VSMK-AI-SOC Automation Tool.\n")
            
        return filepath
